# Playbook to pre-pull all ocp images on all ocp nodes
# Based on disconnected install documentation:
# https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/installing_clusters/install-config-install-disconnected-install

- name: perform docker login
  docker_login:
    username: "{{ rh_user }}"
    password: "{{ rh_password }}"
    registry_url: "https://registry.redhat.io"

- name: pull ocp images set 1
  docker_image:
    name: "registry.redhat.io/openshift3/{{ item }}:{{ ocp_general_tag }}"
  with_items: "{{ ocp3_images_1 }}"

- name: pull ocp images set 2
  docker_image:
    name: "registry.redhat.io/openshift3/{{ item }}:{{ ocp_general_tag }}"
  with_items: "{{ ocp3_images_2 }}"

- name: pull ocp images set 3
  docker_image:
    name: "registry.redhat.io/openshift3/{{ item }}:{{ ocp_general_tag }}"
  with_items: "{{ ocp3_images_3 }}"

- name: pull ocp images set 4
  docker_image:
    name: "registry.redhat.io/openshift3/{{ item }}:{{ ocp_general_tag }}"
  with_items: "{{ ocp3_images_4 }}"

- name: pull ocp images set 5
  docker_image:
    name: "registry.redhat.io/openshift3/{{ item }}:{{ ocp_general_tag }}"
  with_items: "{{ ocp3_images_5 }}"

- name: pull ocp images set 6
  docker_image:
    name: "registry.redhat.io/openshift3/{{ item }}:{{ ocp_general_tag }}"
  with_items: "{{ ocp3_images_6 }}"

- name: pull ocp images set 7
  docker_image:
    name: "registry.redhat.io/openshift3/{{ item }}:{{ ocp_general_tag }}"
  with_items: "{{ ocp3_images_7 }}"

- name: pull etcd
  docker_image:
    name: "registry.redhat.io/rhel7/etcd:{{ ocp_etcd_tag }}"

- name: pull glusterfs
  docker_image:
    name: "registry.redhat.io/rhgs3/rhgs-server-rhel7:{{ ocp_rhgs_server }}"

- name: pull heketi 
  docker_image:
    name: "registry.redhat.io/rhgs3/rhgs-volmanager-rhel7:{{ ocp_rhgs_volmanager }}"

- name: pull gluster block provisioner
  docker_image:
    name: "registry.redhat.io/rhgs3/rhgs-gluster-block-prov-rhel7:{{ ocp_rhgs_block_prov }}" 

- name: pull gluster s3
  docker_image:
    name: "registry.redhat.io/rhgs3/rhgs-s3-server-rhel7:{{ ocp_rhgs_s3_server }}"

